Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  #use '' because referencing homepage
    path('',include('pizzas.urls')),  #include all urls in the mainapp and users folders
]

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),   #individual pizza page
                                                               #<int:pizza_id>: creates an integer variable that references the primary key of pizzas table
    path('new_comment/<int:pizza_id>/',views.new_comment, name='new_comment'),
]

pizzas/models.py
from django.db import models


# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)         #models define the data we want to manage in our app in the form of a class

    def __str__(self):
        return self.name



class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)  #each topping is only assigned to one pizza
    name = models.TextField()

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.name



class Comment(models.Model):       #has fields called pizza, text, and date_added
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'comments'
    
    def __str__(self):
        return self.text

pizzas/forms.py
from django import forms

from .models import Comment

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment              #base the form of the comment model
        fields = ['text']            #don't have to show all fields from topic model
        labels = {'text':''}                
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza
from .forms import CommentsForm

# Create your views here.

def index(request):
    '''Home page for pizzeria'''
    return render(request, 'pizzas/index.html')



def pizzas(request):                 #whatever you named the view in URLs must be received in views with
                                     #the exact same function name
    pizzas = Pizza.objects.order_by('name')
   
    context = {'pizzas':pizzas}                #use context to populate the HTML template with data (pass data to html)
                                               #context is a dictionary- key is variable used in template file, value is variable used in views function

    return render(request, 'pizzas/pizzas.html',context)



def pizza(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)     #urls.py calls a variable called pizza_id which is defined here, SO MUST BE THE SAME
     #calls the Pizza model (class/object)
    toppings = pizza.topping_set.all()         #foregin key accessed using '_set'
    comments = pizza.comment_set.all()         #all() iterates through the database and retreives
    context = {'pizza':pizza, 'toppings':toppings, 'comments':comments}

    return render(request, 'pizzas/pizza.html',context)
                                                        # "." notation pulls the attributes in OOP


def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)    #first, determines which pizza the comment will be written under

    if request.method != 'POST':              #if the request is GET- requesting a form from the webserver
        form = CommentsForm()                 #loads an empty form
    else:
        form = CommentsForm(data=request.POST)  #if the request if POST- take data from the webpage (form) and save it in the (database)
                                                #POST = FILLING OUT THE FORM- WRITING TO DATABASE
        if form.is_valid():
            new_comment = form.save(commit=False)   #tells database we're not ready to write to the form yet
            new_comment.pizza = pizza               #assigns the comment to a pizza
            new_comment.save()
            return redirect('pizzas:pizza',pizza_id=pizza_id)  

    context = {'form': form, 'pizza': pizza}
    return render(request, 'pizzas/new_comment.html',context)

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <title>Pizzeria</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzas:index' %}">Pizzeria</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
        aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pizzas:pizzas' %}">Pizzas</a></li>
        </div>

    </nav>
<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}


{% block page_header %}
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaUqcvw97mVkmsMIckgKrpCo21PKE8028lOg&usqp=CAU">
<div class="jumbotron">
    <h1 class="display-3">Fast. Fresh. Delicious.</h1>
    <p class="lead">Pizzeria shows you a list of available pizzas, lists all toppings associated with each pizza, and allows the user
        to post comments about any particular pizza.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'pizzas:pizzas' %}" role="button">View the menu &raquo;</a>
</div>
<img src="https://totos.com/wp-content/uploads/hero-Totos-Pizzeria.jpg" width='900' height='500'>

{% endblock page_header %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}


<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
<!--includes pizza.id value in the URL so the view function can associate the new comment with the correct pizza-->
<!--user can click on this to get back to the pizza they were in-->

<p>Add a new comment:</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>
    {% csrf_token %}   <!--prevents SQL injection hacks-->
    {{ form.as_p }}    <!--don't have to write out each field, just load form-->

    <button name="submit">Add comment</button>

</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}


<h3>{{ pizza }} Pizza</h3>    <!--pulled from context dictionary in views (pizza is the key)-->
{% if pizza.name == 'Hawaiian' %}
<img src="https://www.jessicagavin.com/wp-content/uploads/2020/07/hawaiian-pizza-16-1200.jpg" width='200' height='200'>
{% elif pizza.name == 'Meat Lovers' %}
<img src="https://www.thespruceeats.com/thmb/P35kji9UfT9JndhurFbPRb1Tuyw=/2998x1999/filters:fill(auto,1)/aqIMG_4568fhor-0b89dc5c8c494ee9828ed29805791c5a.jpg" width='260' height='170'>
{% elif pizza.name == 'Supreme' %}
<img src="https://restaurantclicks.com/wp-content/uploads/2021/09/tasty-supreme-pizza-with-olives-peppers-onions-and-sausage.jpg" width='250' height='200'>
{% elif pizza.name == 'Margherita' %}
<img src="https://www.acouplecooks.com/wp-content/uploads/2018/10/Margherita-Pizza-018.jpg" width='200' height='230'>
{% endif %}


<br>
<br>
<h4>Toppings:</h4>
<ul>
   {% for t in toppings %}     <!--Calls the key of the toppings dictionary in views.py, iterates throguh the dict-->
   <li>
       <p>{{ t.name|linebreaks }}</p>   <!--name is attribute of topping model-->
   </li>

    {% empty %}
    <li>There are no toppings for this pizza.</li>
    {% endfor %}
</ul>


<br>
<h4>Comments:</h4>
<ul>
    {% for c in comments %}
    <li>
        <p>{{ c.text|linebreaks }}</p>
    </li>
    {% empty %}
    <li>There are no comments for this pizza.</li>
    {% endfor %}
</ul>

<p>
    <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a new comment</a>
</p>
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}


<h2><p>Pizzas</p></h2>

<ul>
   {% for p in pizzas %}    <!--Calls the key of the pizzas dictionary in views.py, iterates throguh the dict-->

    <li><h3>
        <a href="{% url 'pizzas:pizza' p.id %}">{{ p }}</a>
    </h3></li>           <!--don't have to write p.name because of the str method in models.py-->

    {% empty %}
    <li>No pizzas have been added yet</li>
    {% endfor %}
</ul>

{% endblock content %}